replicaCount: 1

applicationName: web-configuration
namespace: cardsapi-generic-4

nodeSelector:
  environment: cardsapi-generics

image:
  repository: 261177153744.dkr.ecr.us-east-1.amazonaws.com/arquitetura/configuration-service
  pullPolicy: IfNotPresent
  tag: "RELEASE-1.0.1-0ae4b966"

resources:
  limits:
    cpu: 500m
    memory: 768Mi
  requests:
    cpu: 50m
    memory: 200Mi

service:
  type: ClusterIP
  port: 8888

healthCheck:
  readiness:
    enabled: false
    initialDelaySeconds: 150
    timeoutSeconds: 5
    periodSeconds: 5
    httpGet:
      enabled: false
      path: /actuator/health 
    tcpSocket:
      enabled: false 
  liveness:
    enabled: false
    initialDelaySeconds: 150
    timeoutSeconds: 5
    periodSeconds: 5   
    httpGet:
      enabled: false
      path: /actuator/health   
    tcpSocket:
      enabled: false

persistence:
  enabled: false
  mounts: 
    - mountPath: /var
      name: mount1
   
  volumes: 
    - name: mount1    
      nfs:
        server: dns.com
        path: /example


configmaps:
  enabled: true
  envs:
    #MERCI_AUTH_TOKEN_CLIENT_ID: RHEAGWPMFOB62KESG4GONJTV
    #MERCI_AUTH_TOKEN_CLIENT_SECRET: $$2a$$10$$exIIu.9Egx4TXRc*4mxiqe7Cx6ozgCicOdLkg8Ot7f*a6FBE2dIK2
    SPRING_CLOUD_CONFIG_SERVER_GIT_URI: https://gitlab.prc.rpe.tech/arquitetura/configuration.git
    http_proxy: "http://10.232.77.168:3128/"
    ftp_proxy : "ftp://10.232.77.168:3128/"
    rsync_proxy: "rsync://10.232.77.168:3128/"
    no_proxy: "localhost,127.0.0.1,192.168.1.1,::1,*.local"
    HTTP_PROXY: "http://10.232.77.168:3128/"
    FTP_PROXY: "ftp://10.232.77.168:3128/"
    RSYNC_PROXY: "rsync://10.232.77.168:3128/"
    NO_PROXY: "localhost,127.0.0.1,192.168.1.1,::1,*.local"
    https_proxy: "http://10.232.77.168:3128/"
    HTTPS_PROXY: "http://10.232.77.168:3128/"

ingress:
  enabled: false
  annotations:
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:138511992678:certificate/14f241ee-6dc9-4a70-860e-d1e891f63ab6,arn:aws:acm:us-east-1:138511992678:certificate/908ad1e4-db79-42cf-ab77-c22938424eea
    alb.ingress.kubernetes.io/group.name: lab-rpe-ext
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS13-1-1-2021-06
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/target-type: ip
    kubernetes.io/ingress.class: alb
  host: cardsapiregulatorio.staging.prc.rpe.tech
  path: /cards-api/*
  pathtype: ImplementationSpecific

hpa:
  enabled: false
  scaling:
    minReplicas: 1
    maxReplicas: 3  
  cpu:
    enabled: false
    averageUtilization: 80
  memory:
    enabled: false
    averageUtilization: 80
