{{- if .Values.hpa.enabled }}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.applicationName }}-hpa
  namespace: {{ .Values.namespace }}
spec:
  minReplicas: {{ .Values.hpa.scaling.minReplicas }}
  maxReplicas: {{ .Values.hpa.scaling.maxReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name:  {{ .Values.applicationName }}
  behavior:
    scaleDown:
        stabilizationWindowSeconds: 300
        policies:
        - type: Pods
          value: 1
          periodSeconds: 300
    scaleUp:
        stabilizationWindowSeconds: 300
        policies:
        - type: Pods
          value: 1
          periodSeconds: 300
  metrics:
    {{- if .Values.hpa.cpu.enabled }}
    - type: Resource
      resource:
        name: cpu
        target:
            type: Utilization
            averageUtilization: {{ .Values.hpa.cpu.averageUtilization }}
    {{- end }}
    {{- if .Values.hpa.memory.enabled }}
    - type: Resource
      resource:
        name: memory
        target:
            type: Utilization
            averageUtilization: {{ .Values.hpa.memory.averageUtilization }}
    {{- end }}
{{- end }}



