apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.applicationName }}-sa
  namespace: {{ .Values.namespace }}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::138511992678:role/ParameterStoreAccess-QA




