apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.applicationName }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: http
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.port }}
  - name: web
    port: {{ .Values.service.port2 }}
    protocol: TCP
    targetPort: {{ .Values.service.port2 }}
  selector:
    app: {{ .Values.applicationName }}
  sessionAffinity: None
  type: {{ .Values.service.type }}
